---
- name: install package
  tags: packages,workstation-packages
  package:
    name:
      - libreoffice-fresh
      - hunspell
      - hunspell-en_us
      - hunspell-fr
      - hyphen
      - hyphen-en
      - hyphen-fr
      - libmythes
      - mythes-en
    state: latest
...